### ISSUE TITLE
Publish the solution in Google Cloud Marketplace

### ISSUE THREAD

**Issue by james-w** [jetstack/jetstack-secure-gcm#24]
There are still some final testing and apparently some things that need to be done on the Google
side, but we are close to be able to publish the solution in GCM.

The presentation in the Marketplace can be previewed [on the draft app page](https://console.cloud.google.com/marketplace/details/jetstack-public/jetstack-secure-for-cert-manager__draft)

**Update (mael):** the draft was accepted by Google. The app is published in "private" mode [on the official app page](https://console.cloud.google.com/marketplace/details/jetstack-public/jetstack-secure-for-cert-manager).

**Comment by james-w** [comment]
Yes, I have made the github repo public, so please go ahead and submit for review.

**Comment by maelvls** [comment]
I just clicked the Submit button!

> This solution draft has been submitted and is being reviewed.

**Comment by maelvls** [comment]
Update: the app was accepted on Sat 6 March 2021! It is now visible by anyone that has access to the jetstack-public GCM project [on the official app page](https://console.cloud.google.com/marketplace/details/jetstack-public/jetstack-secure-for-cert-manager).

**Comment by maelvls** [comment]
We seem to be ready to release publicly. This morning, I decided to proceed and untoggle the "Hide solution from end users" checkbox:

![hide-solution (1)](https://user-images.githubusercontent.com/2195781/112135045-a5bb3c80-8bcd-11eb-9e2d-c0bab4743a2c.png)

It looks like Google needs to approve the solution again. So I re-submitted it for review.

**Comment by maelvls** [comment]
The Google Cloud Marketplace app [Jetstack Secure for cert-manager](https://console.cloud.google.com/marketplace/details/jetstack-public/jetstack-secure-for-cert-manager) just [went live](https://groups.google.com/a/jetstack.io/g/cert-manager-maintainers/c/lQo2Ct5VMt4/m/6Oy6e2FsBgAJ)! 🎉

Took some time to get there but it is finally public!

I'll ask as many Jetstackers as possible to try it out. https://github.com/jetstack/platform-board/issues/338 needs to be completed first so that people at jetstack can try it out (the "Purchase app" requires the billing admin privilege). I pinged Zee about this.
